spring.application.name=api

dotenv.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/condolives
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.open-in-view=false

spring.flyway.enabled=false

jwt.secret=CasU1RUhtwhvr1M20dsdaX120X210L21jtmtmvT21TU2WTWQER19T21JIJDFU9J91U2JR9zvxZAWEFW12JSKR2TJ2J984WWQT2517FADS9JFAUSNAZMJCASM
jwt.expiration-ms=86400000